cmake/RepositoryDependenciesSetup.cmake, unit_tests/testTPLSLEPC/testTPLSLEPC.f90
=> No petsc build

src/Geom_Poly.f90, unit_tests/testGeom_Poly/testGeom_Poly.f90
Description: The Polygonize_Cylinder routine is similar
to the already-existing Polygonize_Circle routine.
Test for cylinder added to Geom_Poly unit test.
CASL Ticket # - PHI #3970
=> Polygonize_Cylinder routine added.

src/ODESolverTypes.f90
This fixed the intel compiler bug
=> Two line fix to work around intel 13 compiler bug

src/IOutil.f90, src/VTUFiles.f90, unit_tests/testIOutil/testIOutil.f90, unit_tests/testVTUFiles/testVTUFiles.f90
Small change made for organizing VTU outputs into folders.
=> VTU FSR outputs are now organized by domain into folders.

.travis.yml, src/AndersonAcceleration.f90, src/ArrayUtils.f90, src/BLAS2.f90, src/EigenvalueSolverTypes.f90, src/FileType_HDF5.f90, src/MatrixTypes_Trilinos.f90, src/ParallelEnv.f90, src/PreconditionerTypes.f90, src/trilinos_interfaces/trilinos_pc.hpp, unit_tests/testPreconditionerTypes/testPreconditionerTypes.f90, unit_tests/testUnitTest/testUnitTest.f90
Removes unused variables from recent changes.
=> Removes compilier warnings from unused variables

src/MatrixTypes_PETSc.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90, unit_tests/testTPLPETSC/testTPLPETSC.f90
Want to see if this passes the CI which uses the VERA TPLs docker container.
=> Adding PETSc matrix transpose testMatrixTypes

src/PartitionGraph.f90
Description:
Patch sent to me by Andrew
=> Fixes defs for uninit vars in PartitionGraph

src/IO_Strings.f90, unit_tests/testIOutil/testIOutil.f90
This helps the VTU stuff, and should have been done forever ago.
=> Adding implementation of SlashRep for StringTypes

src/MemProf.f90
Some updates to memprof:
* can turn edits on and off
* can set a threshold for the minimum change that will edit the memory
* has a verbose mode which will edit all of the data for each process.
=> Memprof update

src/Constants_Conversion.f90
Added Bar2MPA, kg2g, and m2cm.
=> Adds 3 new conversions to Constants_Conversion

src/FileType_HDF5.f90
Updating FileType_HDF5 to work with HDF5 1.10.1.
CASL Ticket # - 5341
=> Updating FileType_HDF5 to work with HDF5 1.10.1.

src/PartitionGraph.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90
Improved robustness of refinement methods.
Created functions for some common blocks of code.
More reasonable memory allocation for recursive methods.
=> Partition graph cleanup

src/FileType_HDF5.f90, unit_tests/testHDF5FileType/testHDF5FileType.f90
This includes the fixes for issue_74 merge request, which was not built on the correct version of the repo.
=> Add new file status to allow overwriting HDF5 datasets

src/ParallelEnv.f90
Adds broadcast generics to MPI_Envtype for scalar real values
=> Adds broadcast generics to MPI_Envtype for scalar real values

src/MeshTransfer.f90, unit_tests/testMeshTransfer/testMeshTransfer.f90
Description:
Run into compiler issues without it.
Needed to add dependencies to the unit test.
=> Need the Private attribute in the MeshTransfer Module.

src/LinearSolverTypes.f90
Missed variable name change for Belos_SetConvCrit.
=> convTol Belos_SetConvCrit

src/MatrixTypes_Native.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90
=> Revert "Add exceptions to MatrixType"

src/IO_Strings.f90, unit_tests/testIOutil/testIOutil.f90
Description:
This feature is needed for the material changes in XMLProc for ticket
5527.  I need an option to search through the array in reverse order.
Added an optional argument and tests to the strarraymatchind and
strarrayeqind routines.
CASL Ticket # - PHI 5527
=> Adding optional lreverse argument to strarrayeqind routines.

src/ParallelEnv.f90, unit_tests/testParallelEnv/testParallelEnv.f90
Adds wrapper routines for MPI_send(recv) for character, integer, and real data types
=> Add mpi wrappers

src/ElementsIsotopes.f90, unit_tests/testElementsIsotopes/testElementsIsotopes.f90
I added a small subroutine to ElementIsotope to check whether or not a string is a valid isotope ID.
=> Is valid element iso

src/VectorTypes_Trilinos.f90
Added set and getSelected for Trilinos vector type (just encounters error).
=> Hotfix Trilinos Vector

src/ArrayUtils.f90, src/FileType_HDF5.f90, src/Geom_Graph.f90, unit_tests/testArrayUtils/testArrayUtils.f90, unit_tests/testExpTables/testExpTables.f90, unit_tests/testGeom_Graph/testGeom_Graph.f90, unit_tests/testHDF5FileType/testHDF5FileType.f90
Addresses remaining Valgrind errors in 4 Futility tests.
=> Valgrind fixes

src/FileType_HDF5.f90
=> Revert "Fix valgrind defects in FileType_HDF5"

src/CMakeLists.txt, src/IO_Strings.f90, src/SpeciesElements.f90, unit_tests/CMakeLists.txt, unit_tests/testSpeciesElements/CMakeLists.txt, unit_tests/testSpeciesElements/testSpeciesElements.f90
This adds a class to help with Thermochimica coupling
=> Edits for thermochimica coupling

src/Constants_Conversion.f90
=> Adding conversion for eV to J.

src/IO_Strings.f90, unit_tests/testIOutil/testIOutil.f90
Reverts CASL/Futility#171
Should have held this till after the tag.  We'll redo once tag is complete.
=> Revert "Implement float utility for counting digits left of decimal"

src/NonLinearSolver.f90, unit_tests/testNonLinearSolver/testNonLinearSolver.f90
Adds a bit of user control and documentation to the nonLinearSolver module
=> Non lin solver

src/ElementsIsotopes.f90, src/Strings.f90, unit_tests/testElementsIsotopes/testElementsIsotopes.f90
Also adds a new assignment interface for stringTypes to assign
a 1D array of length-1 characters to a single stringType to make
a few things simpler.
CASL Ticket # - 5907
=> Adds isValidElemName to ElementsIsotopes

src/ExceptionHandler.f90, src/ParameterLists.f90, unit_tests/testExceptionHandler/testExceptionHandler.f90, unit_tests/testParameterLists/testParameterLists.f90
Adding a modified verify subroutine for development use.  The original verify was only able to be used for unit tests.
=> Pl verify list

src/Strings.f90
Adding an assign_cchar_to_string interface.
=> assign_cchar_to_string

src/Strings.f90
=> Revert "assign_cchar_to_string"

src/Strings.f90, unit_tests/testStrings/testStrings.f90
Resolves an issue with calculating the size of the outgoing StringType
=> Applies a fix for the cchar to fchar interface

src/PartitionGraph.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90
=> Revert "Partition graph metrics update"

.travis.yml
Turns on DBC for Travis CI as a part of pre-push testing.
=> Turning on DBC for Travis-CI

src/FileType_Fortran.f90, src/IO_Strings.f90, unit_tests/testFileType_Fortran/testFileType_Fortran.f90, unit_tests/testIOutil/testIOutil.f90
Adding functionality to write a 2-D string array as a table on the fortran file type.
=> Write table on fortran file type.

src/ParameterLists.f90, unit_tests/testParameterLists/testParameterLists.f90
Routine to convert parameter list of parameter lists to a table.
=> Convert PL to 2D string array

src/FileType_HDF5.f90, src/IO_Strings.f90, src/Strings.f90, unit_tests/testIOutil/testIOutil.f90, unit_tests/testParameterLists/testParameterLists.f90, unit_tests/testStrings/testStrings.f90
Clean up formatting, Remove defunct routines. This commit resolves #217
=> Strings cleanup

src/Strings.f90, unit_tests/testStrings/testStrings.f90
Implements a StringType partition functions similar to that encountered in python.
=> Implements string partition function

src/Geom_Poly.f90, unit_tests/testGeom_Poly/testGeom_Poly.f90
=> Add code to rotate polygon objects in 90-degree increments

src/ExceptionHandler.f90
This file was originally passed over when addressing the rest of
Futility due to an in progress pull request.  However, the pull
request has since been closed without being merged, so the indentation
needed to be updated in this module still.
CASL Ticket # - 6222
=> Updates indentation in ExceptionHandler to conform to code standard

src/IOutil.f90, src/ODESolverTypes.f90, src/PreconditionerTypes.f90, src/TAU_Stubs.f90, src/VectorTypes.f90
Description:
Fixed errors flagged by Intel 19
CASL Ticket # - 6264
=> Changes to get Futility working with Intel19 compiler

src/IO_Strings.f90, src/Sorting.f90, src/Strings.f90, unit_tests/testIOutil/testIOutil.f90, unit_tests/testSorting/testSorting.f90, unit_tests/testStrings/testStrings.f90
Adds equality operators for strings, string sorting,
and string duplicate removal
=> String Sorting

src/AndersonAcceleration.f90, src/VectorTypes.f90, unit_tests/testAndersonAcceleration/testAndersonAcceleration.f90, unit_tests/testVectorTypes/testVectorTypes.f90
Implements a fully native arbitrary depth Anderson acceleration algorithm with efficient (direct) calculation of Anderson coefficients.
=> Native Anderson Acceleration

.travis.yml
Initially testing to see if this works on travis
=> Add python packages to travisci

src/AndersonAcceleration.f90
Had one last parameter list that needed clearing that was not. This fixes that oversight.
=> Memory Leak Fix for Anderson

src/AndersonAcceleration.f90
Fixes bad usage of ifdef. Changed to actually handle 2 conditions.
=> Fixed bad ifdef check

src/ODESolverTypes.f90
=> Newton iteration convergence check in bdf ode step

src/LinearSolverTypes.f90, unit_tests/testLinearSolver/testLinearSolverParallel.f90, unit_tests/testMatrixTypes/testMatrixTypesParallel.f90
Simple fixes, just involved clearing some parameterlists. Just careless mistakes.
=> Resolved Valgrind errors in testLinearSolver and testMatrixTypes

src/PartitionGraph.f90
=> Resolves gcc 8.4.0 build error

src/IO_Strings.f90, unit_tests/testIOutil/testIOutil.f90
Adds string conversion interface for logicals
=> Add str_SBK to str interface

src/ArrayUtils.f90, src/Search.f90, unit_tests/testArrayUtils/testArrayUtils.f90, unit_tests/testSearch/testSearch.f90
Description:
Fixing another issue with array utils assigning the first value as
unique, even if it is null.  Changing that to loop over all values
instead.
CASL Ticket # - PHI 6419
=> Adding subroutines for Find interface for searching strings.

src/ArrayUtils.f90, unit_tests/testArrayUtils/testArrayUtils.f90
Removes an entry from an array
=> Adds pop_entry interface to ArrayUtils

src/ParallelEnv.f90, unit_tests/testParallelEnv/testParallelEnv.f90
Adds a wrapper in parallel env which works similarly to mpi_gather for futility string types..
=> Add gather collective for StringTypes

src/Strings.f90, unit_tests/testStrings/testStrings.f90
Simplify some of the operations in the string to integer and string to float routines and add testing.
=> Simplify string conversions

src/ParallelEnv.f90
The tags needed to be incremented for every element of the array instead of only when a send occurred.
=> Tags were being calculated incorrectly for more than 2 procs

src/ExtendedMath.f90, src/Geom_Box.f90, src/Geom_CircCyl.f90, src/Geom_Points.f90, src/Geom_Poly.f90, unit_tests/testExtendedMath/testExtendedMath.f90, unit_tests/testGeom_Box/testGeom_Box.f90, unit_tests/testGeom_CircCyl/testGeom_CircCyl.f90, unit_tests/testGeom_Points/testGeom_Points.f90, unit_tests/testGeom_Poly/testGeom_Poly.f90
Description:
These functions are needed to help speed up the geometry processing in
MPACT.
VERA-dev Issue # - ####
=> Adding overloaded assignments for geometries, and 90 degree rotation.

.travis.yml
Specifies python 2.7 in the get-pip URL
=> Fix path to get-pip

src/IAPWS_WaterProperties.f90
Fixes an uninitialized variable conditional jump in IAPWS
=> Fix uninitialized value in IAPWS module
