src/LinearSolverTypes.f90
Note that the "MG" preconditioner is not actually a multigrid preconditioner.
Since no information is provided about the grid, it is just doing one
smoother step with the default smoother, which appears to be a Cholesky
iteration.
=> Add "EISENSTAT" and "MG" PETSc preconditioner options.

src/FileType_HDF5.f90
Description:
When calling the close operation for an HDF5 file the file's
exception handler is set to not stop on errors. However,
the stop on error property is not reset after the file is closed.
This causes problems when an HDF5 file is open and closed and
reopened during execution.
CASL Ticket # - #4776
=> Fixing hdf5 file exception handler behavior after close

src/ODESolverTypes.f90
Jack Galloway was noticing run-away memory when using the ODE solver.  I couldn't reproduce the issue but these types need to get cleared anyway.
=> Adding clear and deallocate statements for vectors

src/LinearSolverTypes.f90, unit_tests/testLinearSolver/testLinearSolver.f90
Current implementation would clear and deallocate the preconditioner whenever the matrix
is changed or the solver failed.  This ends up spending significant time in parameter list
and allocation time for mongoose which is solving a temperature equation many many times
per solve.  The changes represent about an order of magnitude speedup in mongoose.
=> Stop deallocating LU factorization all the time

src/LinearSolverTypes.f90
This means that, when a PETSc linear solver is called, the solution vector
passed to PETSc should be initialized.  This should be true in all CASL codes
and, if that's not the case, then the other codes should be changed so that
calls to PETSc solvers are always made with an initialized solution vector. To
preserve the same behavior, simply pass PETSc a solution vector initialized to
zero.
Previously, in many places where we already had a good estimate of the flux, we
were throwing away this information by starting with a naive guess of zero.
This change should reduce the number of linear solver iterations required for
convergence in all places where GMRES is called and a reasonable estimate of
the solution is known.
=> Make PETSc use a nonzero initial guess by default.

src/LinearSolverTypes.f90, unit_tests/testLinearSolver/testLinearSolver.f90, unit_tests/testParTPLPETSC/testParTPLPETSC.f90
Adding hooks to direct LS type to use SuperLU.  Right now, this is enabled by specifying PETSC as the TPL and LU as the solver method.
=> SuperLU Linear Solver

src/IntrType.f90
Without this, the functions do not work for array inputs (they can evaluate to
false even if there are nan's present).  There are already places in MPACT
where isNaN and isInf are assumed to be elemental.
=> Make isNaN and isInf functions elemental.

src/ODESolverTypes.f90, unit_tests/testODESolver/testODESolver.f90
The sundials fortran interface effectively defines a singleton object
for the ode solver.  Since multiple ODE solvers are needed in Mongoose
in order to solve multiple pins at once.  This requires a lot of sundials
data to be global across all ODE solver types so module data structures are
used to hold a few logicals and data arrays that sundials requires.  Note that
this fix will only work if all ODE solvers have the same number of unknowns.
A better and more permanent fix would be to use the PETSc wrapper for
sundials or directly wrap the C interface for sundials if multiple size ODE solvers
are needed.
=> Update sundials ode solver to support multiple ODE solver objects

src/IOutil.f90, unit_tests/testIOutil/testIOutil.f90
Description:
This implements a fairly portable make directory interface for
Fortran. Works for GNU and Intel.
Should work in Windows, but have not tested it there yet.
=> Adding routine to IOutil for mkdir

cmake/Futility_Configurations.cmake
We were using Ofast which enables non-standards-compliant optimizations.
Namely flushing subnormal floats to zero, which was causing actual
issues in some cases. The only remotely safe optimization is the
-fstack-arrays, which has also bit us a couple of times.
=> Change release flag for GNU from Ofast to O3

src/DBC.h, unit_tests/testDBC/testDBC.f90
Aaron discovered that having DBC_ in front of ENSURE and REQUIRE messes up the line numbers in gfortran 4.8.
It appears that pretty much any other combintation will not result in having the wrong line numbers.  He
tried not having DBC_, using ABC_, appending _DBC, even appending DbC_, and several other combinations.
Since the previous review made prepending DBC_ as optional, I'm reverting the names back to the original name.
=> Removes DBC_ from REQUIRE and ENSURE interface

src/PartitionGraph.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90
Description:
Changes to REB partitioning algorithm to give more convex domains. Updated unit-test.
Additionally, some quality changes.
1. Consider weight AFTER finding next expansion vertex (then determine whether to expand)
2. Only search neighboring vertices not already in domain
3. Rather than distance from original vertex, now takes distance from a reference point:
i. Reference point starts as original vertex
ii. If weight of external connections decreases (from previous expansion) switch reference point
to the expansion.
CASL Ticket # - #5029
Updated PartitionGraph unit-test
Description:
Updated PartitionGraph unit-test to reflect changes in previous REB commit.
CASL Ticket # - #5029
=> Changes to REB partitioning algorithm.

src/VTUFiles.f90, unit_tests/testVTUFiles/testVTUFiles.f90
Description:
Character types can be variable length if they are dummy arguments.
These don't need to be changed to strings.
=> Hotfix for changing characters to strings

src/Allocs.f90, unit_tests/testAllocs/testAllocs.f90
When using certain options in MPACT, the memstring variable returned
by getMemUsageChar_default had an unreadable value that caused an
ungraceful crash.  While this may ultimately be an issue with the
usage of Allocs in MPACT, these changes both eliminated redundant
code and resolved the ungraceful exit in MPACT.
=> Fixes an issue with getMemUsage in Allocs

src/FileType_HDF5.f90, src/ParameterLists.f90, unit_tests/testHDF5FileType/testHDF5FileType.f90
Description:
In an attepmt to eliminate erroneous characters being printed for a
null/empty string type on a parameter list, the parameter list value is
checked to make sure it has a length > 0 before printing.  If it is ==
0, an empty string is printed (i.e. '') in its place.
CASL Ticket # - PHI #5241
=> Checking if the string variable is len_trim > 0 before writing.

src/IntrType.f90
This reverts commit a126822521ac5a01d82e9f4c262d0e66bbd3d9ae.
The functionality this commit added was deemed redundant, so we
are removing it.
=> Revert "Adds .XOR. operator for logicals to IntrTypes"

src/DBC.f90, src/DBC.h, unit_tests/testDBC/testDBC.f90
Description:
For client code that will use DBC, it would have to add two lines:
#include "DBC.h"
USE DBC
I've modified "DBC.h" to to include the USE statement when
FUTILITY_DBC is defined. Now client code wanting to use DBC should
just do:
MODULE client
#include "DBC.h"
...
Also:
* made indentation consistent with other source files
* changed variable definitions to avoid unnecessary implied save
attribute
CASL Ticket # - #5200
=> Simplify usage of DBC

src/DBC.h, src/FileType_HDF5.f90, unit_tests/testDBC/testDBC.f90, unit_tests/testHDF5FileType/testHDF5FileType.f90
This should just about fix any instance of of the following going forward:
```
HDF5-DIAG: Error detected in HDF5 (1.8.10) MPI-process 183:
#000: H5Dio.c line 174 in H5Dread(): can't read data
major: Dataset
minor: Read failed
#001: H5Dio.c line 449 in H5D__read(): can't read data
major: Dataset
minor: Read failed
#002: H5Dchunk.c line 1735 in H5D__chunk_read(): unable to read raw data chunk
major: Low-level I/O
minor: Read failed
#003: H5Dchunk.c line 2766 in H5D__chunk_lock(): data pipeline read failed
major: Data filters
minor: Filter operation failed
#004: H5Z.c line 1120 in H5Z_pipeline(): filter returned failure during read
major: Data filters
minor: Read failed
#005: H5Zdeflate.c line 136 in H5Z_filter_deflate(): memory allocation failed for deflate uncompression
major: Resource …
```
=> Fix hdf5 mem usage

src/ParallelEnv.f90
In two routines, a value was being set after a DBC check, causing
stochastic failures.  The value was already being set in the wrong order,
but it does not currently get used in the MPI call, so the error showed
up only in the DBC checks.  I've left the unused value and optional
argument in place since I assume they were first added with some
intention to use them.
=> Fix valgrind defects in ParallelEnv

src/trilinos_interfaces/trilinos_pc.cpp
When we switched from ML to MeuLu, the ML Default Type parameter was
added to the incorrect parameter list, which is why it didn't cause issues.
This change gets rid of that parameter completely because multigrid algorithm
does the same thing.  sa: damping factor was also defined twice so the second
was not being used, yet the first value was incorrect and the second was correct
so I removed the first entry.
Ticket #3663
=> Fixes to MeuLu parameter list

src/ParallelEnv.f90
Methods such as gather, scatter, bcast, etc. don't actually
modify the MPI_EnvType they're called on, so the INOUT intent
was more restrictive than it needed to be.  This caused some
issues in client code.
=> Change INTENT(INOUT) to INTENT(IN) for MPI_EnvType interfaces

src/Geom_Box.f90, unit_tests/testGeom_Box/testGeom_Box.f90
are optional, preserving any pre-existing uses of this type.
=> Adds 3D capability to the ABBoxType.  All 3D arguments and funcitonality

src/LinearSolverTypes.f90, unit_tests/testLinearSolver/testLinearSolver.f90
Description:
As part of restructuring reinitLS to only reinit the matrix, KSPSetOperators needs to be callable.
CASL Ticket # - 5106
=> Creating a wrapper for PETSc call KSPSetOperators.

src/EigenvalueSolverTypes.f90, src/LinearSolverTypes.f90, src/MatrixTypes_PETSc.f90, src/ODESolverTypes.f90, src/ParallelEnv.f90, src/PartitionGraph.f90, src/PreconditionerTypes.f90, src/VectorTypes.f90, src/VectorTypes_PETSc.f90, unit_tests/testEigenvalueSolver/testEigenvalueSolver.f90, unit_tests/testLinearSolver/testLinearSolver.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90, unit_tests/testODESolver/testODESolver.f90, unit_tests/testParTPLPETSC/testParTPLPETSC.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90, unit_tests/testPreconditionerTypes/testPreconditionerTypes.f90, unit_tests/testTPLPETSC/testTPLPETSC.f90, unit_tests/testTPLSLEPC/testTPLSLEPC.f90, unit_tests/testVectorTypes/testVectorTypes.f90
Already ran this against petsc 3.6.4 (which CASL is moving to):
100% tests passed, 0 tests failed out of 50
Subproject Time Summary:
Futility    =  78.24 sec*proc (50 tests)
Total Test time (real) =  13.81 sec
=> Changing load statements to point to correct path for petsc 3.6

src/PartitionGraph.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90
Description:
RMS did not have 1/n inside the square root, thus it was more of a
2-norm. This has been fixed by adding the 1/n.
CASL Ticket # - #5014
=> PartitionGraph - Fixed RMS to actually be RMS rather than 2-norm.

src/LinearSolverTypes.f90, unit_tests/testLinearSolver/testLinearSolver.f90
Splitting convTol into relative and absolute.  Native solvers use absolute, but TPLs (like PETSc) can use both.
=> Split convTol

unit_tests/testLinearSolver_Multigrid/testLinearSolver_Multigrid.f90
Adding full header logic to testLS_MG to account for PETSc 3.6+.
=> Hotfix testLS_MG

src/MemProf.f90, src/getSysProcInfo.c
Description:
Using /proc/self/status VmRSS for the resident set size (RSS) versus
the VmSize parameter. The VmSize parameter will include memory from
shared libraries not explicitly allocated to physical memory or by
the program. This can lead to artificially high values that obfuscate
the actual memory usage.
The maximum memory (high water mark for the resident set size) is
also now utilized in the MemProf.f90 module. Previously it was just
the maximum value of VmSize.
Units are also now correct. Raw measurements in getSysProcInfo
are returned as "kilobytes" for peakUsage and "kB" for the RSS.
Generally:
kilobytes = 1000 bytes (or 1024 bytes, it is ambiguous)
kB        = 1000 bytes (may be used erroneously)
KB        = 1024 bytes (may be used erroneously)
KiB       = 1024 bytes …
=> Modification to MemProf to use better edit values

src/MatrixTypes_Native.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90
Integrating the native solvers for sparse matrices would have went more smoothly if Futility would have warned me that I needed to call setShape before setting data and that the j values need to be in ascending order.  Added a few other exceptions that should help prevent unintended behavior.
=> Add exceptions to MatrixType

src/FileType_Fortran.f90, unit_tests/testFileType_Fortran/testFileType_Fortran.f90
Is this okay to make this guarantee?  If I know it's negative 1 when the file wasn't opened, I can use iostat to allow the code to catch and ignore errors when I don't want to write to the file.
=> Update header doc to clarify a return value

src/IO_Strings.f90, unit_tests/testIOutil/testIOutil.f90
Description:
Quoted strings were truncating the number of fields by 1.
Test updated to test quoted strings. This had been commented out. Quoted
strings also tested for multiples.
=> Bug fix in nFields

src/ParallelEnv.f90, unit_tests/testParallelEnv/testParallelEnv.f90
This is intended to store a device ID for offloading calculations
to and accelerator.  The immediate use will be for the GPU system
ID in conjuction with Kokkos, but there could be other uses as well.
=> Adds deviceID component to ParallelEnvtype

src/PartitionGraph.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90
These changes were made to make the automated spatial decomposition process more robust.
These changes were tested on 5a-2d for 1-257 processors. Each case is able to create a valid decomposition map.
=> 5029 robustness

src/Constants_Conversion.f90
Description:
Avogadro's number is changed to 6.022140857e+23 from web page:
[https://physics.nist.gov/cgi-bin/cuu/Value?na](https://physics.nist.gov/cgi-bin/cuu/Value?na)
CASL Ticket # - #5478
=> Avogadro's number is changed to 6.022140857e+23 from Source NIST.

src/Futility_DBC.f90, unit_tests/testDBC/testDBC.f90
Description:
Skip calling MPI_get_rank and MPI_get_nproc if not so it doesn't cause a
misleading error.
=> Have Futility_DBC check if MPI is intialized

cmake/Futility_Configurations.cmake
Description:
This commit is a starting point, and by no means comprehensive.  Most of the
GNU compiler options had an equilvalent NAG option and were replaced accordingly.
The remaining ones were commented out.
=> Adding NAG Compiler options for Futility.

src/MatrixTypes_Native.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90
Readding Bob's matrixtype DBC checks.  These were originally reverted become it was failing other tests in MPACT, but those should be resolved now.
=> Readd MatrixType DBC Checks (#5462)

src/ParallelEnv.f90, unit_tests/testParallelEnv/testParallelEnv.f90
The same is true for the integer versions of all those interfaces.
Those interfaces were also turned into generics so that both
integers and reals can be passed through the same allReduce procedure
name.
=> Adds scalar interfaces for allReduce, allReduceMax, allReduceMin

src/VectorTypes_Base.f90, src/VectorTypes_Native.f90, src/VectorTypes_PETSc.f90, unit_tests/testVectorTypes/CMakeLists.txt, unit_tests/testVectorTypes/testVectorTypes.f90, unit_tests/testVectorTypes/testVectorTypesParallel.f90
Description:
The original getAll procedure will not work for a parallel vector because it
will cause an out of bounds error in PETSc.  To get all values at once, the user
needs to pass in the global indices of the values to get and they can only
pass  in indices that belong to the proc.  I added a new procedure, 'getSelected',
which can be used to do this, clarified that getAll should not be used for parallel
vectors, added tests for getSelected, and then added a new set of parallel vector
tests.
=> Add new getAll procedures for parallel vectors

src/MatrixTypes_Base.f90, src/MatrixTypes_Native.f90, src/MatrixTypes_PETSc.f90, src/MatrixTypes_Trilinos.f90, unit_tests/testMatrixTypes/CMakeLists.txt, unit_tests/testMatrixTypes/testMatrixTypes.f90, unit_tests/testMatrixTypes/testMatrixTypesParallel.f90
Description:
Allows the user to build a matrix row-by-row instead of one element
at a time, which can be much faster.
=> Adding setRow for distributed and sparse matrix types

src/FileType_HDF5.f90, unit_tests/testHDF5FileType/testHDF5FileType.f90
Also adds error checks to ensure that new data sill fit into the
current data type and data set sizes when overwriting pre-existing
data sets.  Updated the test accordingly.
=> Fix valgrind defects in FileType_HDF5

src/EigenvalueSolverTypes.f90, src/PartitionGraph.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90, unit_tests/testTPLSLEPC/testTPLSLEPC.f90
Description:
Like versions >=3.6 of PETSc the location of the Fortran include
directories changed. The ifdefs are modified to work with newer
and older versions of SLEPc like with PETSc.
The usage of EPSComputeError also changed. Therefore, this was
updated.
CASL Ticket # - #5077
=> Fixing SLEPc usage for >= version 3.6

src/MeshTransfer.f90
When passing in 0th order polynomial, no integration was performed.
Also made some minor corrections to some in-code documentation
=> Fix a bug in meshTransfer related to the Legendre polynomial integration

cmake/Futility_Configurations.cmake
This will remove all the spurious warnings from using FINAL procedures.
The warnings that -W-surprising normally covers are for pretty strange,
unusual situations, so we're not really losing any useful information by
disabling this.
=> Adds -Wno-surprising flag to GNU Fortran_FLAGS

src/IO_Strings.f90, unit_tests/testIOutil/testIOutil.f90, unit_tests/testVTUFiles/testVTUFiles.f90
This is a common function in other languages and extremely useful for
standard IO, error handling, and parameter list manipulations, among
other things.  By default it uses the minimum number of spaces for
integers and scientific notation for reals, with 7/15 decimal places
for single/double precision, respectively.
It may be useful to add other formatting options at some point, but
this simple implementation will still be useful in the near term.
=> Implement str(...) function to convert integers and reals to strings

src/CommandLineProcessor.f90
This change was made to support some cleanup in MPACT,
but in general passing a parameter list to the commandline
processor is something that makes sense and could be useful
to other applications down the road.
=> Adds optional plist argument to ProcCmdLineArgs

src/ArrayUtils.f90, unit_tests/testArrayUtils/testArrayUtils.f90
Description:
The default behavior of this routine used the .APPROXEQ. comparison,
which can be too fine in some circumstances.  Default tolerance is
EPSREAL.
Added unit tests for optional input.
=> Adding an optional tolerance argument to the getUnion subroutine.

src/IO_Strings.f90, unit_tests/testIOutil/testIOutil.f90
When calling str(0), there was a LOG10(0) call to calculate the
length, which caused the runtime error.
=> Fix potential infinite memory allocation in str(...) interface

src/Geom_CircCyl.f90, unit_tests/testGeom_CircCyl/testGeom_CircCyl.f90
Description:
The bug is when a line segment is near a circle, is non-tangent to the
circle, but if extended would be.  The intersection routine would
produce a point, but ultimately, the intersection point needed more logic
to determine if the intersection point is outside the circle.
CASL Ticket # - PHI 5083
=> Fixing the intersection between the line type and circle type.

src/UnitTest.f90
For parallel tests, if some procs had 0 asserts and some had
more than 0, a deadlock would occur.  Fixed by removing the IF
statements and allowing all procs to communicate their passes
and failures even if 0 asserts were hit.  No harm in printing
an empty subtest.
Also fixed a typo.
=> Fix potential deadlocks in UnitTest.f90

src/MemProf.f90
Description:
Always associate the parallel env object in MemProf, even if the log file
is not associated.  This will prevent seg faults when the log file is not
associated.
=> Move associate statement

src/FileType_Fortran.f90, src/Times.f90, src/VTKFiles.f90, unit_tests/testVTKFiles/testVTKFiles.f90
Adds changes to improve the efficiency of generating large FSR VTK files.  Namely, the act of repeatedly adding VTK meshes together can be very slow.  This change allows client code to add an array of them together, which is much more efficient.
A couple other minor cleanup items are also added: improved error messages for files and a fix to a bad comment in Times.f90.
=> Improve vtk efficiency

src/ExceptionHandler.f90, unit_tests/testExceptionHandler/testExceptionHandler.f90
Description:
Prior to this, if a message passed to raiseWarning exceeded 512 characters,
it would crash the code due to a IO error.  This fix will truncate the end
of the message in this case.
CASL Ticket # - 6064
=> Fix for very long warning messages

.travis.yml, build_scripts/build_on_docker.sh
Description:
In bash when chaining commands, the && will only execute the next
command if the previous command had a return value of 0. When using
; it will execute the next command regardless of the return code.
Not sure how TravisCI treats the error code in reporting errors,
so I'm hoping this reveals the issue.
Github Issue - #132
=> Changing .travis.yml to use && instead of ;

cmake/Futility_CreateUnitTest.cmake, cmake/SetTestLabels.cmake, unit_tests/testDBC/CMakeLists.txt
In ctest, we can specify categories for unit tests and set which ones get run with a flag (i.e. ctest -L BASIC).
This patch adds all unit tests to the BASIC category so that all configurations (heavy, nightly, continuous, basic) know to run them when passed the -L flag.
=> Mark unit tests appropriately for build system

src/PartitionGraph.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90
Updating the partition graph type to have a weighting factor and the %metrics routine to return the max fraction of processor dependent source regions divided by the total number.
=> Partition graph metrics update

src/PartitionGraph.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90
Description:
Adding %wtfactor attribute used to scale the %wts in the input.  The
default is 1.0.
Adding optional argument to %metrics() routine for the max number of
source regions ratio for the given decomposition.
=> Updating Partition Graph %metrics routine and adding %wtfactor

src/ArrayUtils.f90, unit_tests/testArrayUtils/testArrayUtils.f90
Per Issue #125, GCC 7+ does resets bounds of native arrays when passed through an interface.  `checkBound` relies on this functionality, so the checking of bounds is being deferred to clients.
=> Removing boundCheck as it relies on non-standard functionality (#6172)

src/FileType_HDF5.f90, src/IO_Strings.f90, src/Strings.f90, unit_tests/testIOutil/testIOutil.f90, unit_tests/testStrings/testStrings.f90
Implements `%replace()` method as a generic. One implementation takes a starting index and optionally a stopping index replacing everything in between with repetitions of a supplied character pattern. The other replaces all occurrences of a specified pattern with a replacement pattern.
To do this it became advantageous to implement `%split()` generically as well. The first implementation, without arguments uses a single space as the delimiter and consumes consecutive delimiters returning an array of strings containing no empty strings. The other implementation utilizes a user supplied delimiter. This does not consume consecutive delimiters and instead returns a string array which may contain empty strings where consecutive delimiters occurred. If the delimiter is not found then both …
=> Implements string replace method and testing

src/FutilityComputingEnvironment.f90, unit_tests/testFutilityComputingEnvironment/testFutilityComputingEnvironment.f90
In routines adding or removing timers, changed
TYPE(TimerType) to CLASS(TimerType) in order to match the TimerPtrArray
specification.
When compiling with gcc 4.8.5 the following error was found, along with similar errors in other routines.
```
/home/apfitzge/MPACT/Futility/src/FutilityComputingEnvironment.f90:143.2:
timer => this%getTimer(name)
1
Error: Different types in pointer assignment at (1); attempted assignment of CLASS(timertype) to TYPE(timertype)
```
this change allows compilation to succeed and all unit-tests pass.
=> Fixed compilation issue with FutilityComputingEnvironment for gcc 4.8.5

src/BLAS2.f90, src/MatrixTypes.f90, src/MatrixTypes_Base.f90, src/MatrixTypes_Native.f90, src/MatrixTypes_PETSc.f90, src/Sorting.f90, src/VectorTypes.f90, src/VectorTypes_Base.f90, src/VectorTypes_Native.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90, unit_tests/testMatrixTypes/testMatrixTypesParallel.f90, unit_tests/testSorting/testSorting.f90, unit_tests/testVectorTypes/testVectorTypesParallel.f90
This branch is the first in a series of 3, split off from the bandMat_pGMRES_rsor branch.
These changes pertain to the creation of new parallel datatypes (3 banded matrix types and 1 distributed vector type) with the associated MatVec/dot/norm routines.
=> Adds a set of Native/Parallel Datatypes

src/VectorTypes.f90
An error occurred when MPI is used and PETSc is turned off. Only VectorTypes.f90 had the issue.
=> Enabling MPI when PETSc is not used.

cmake/ProjectCompilerPostConfig.cmake
=> Fixes case where Kokkos isn't setting the host space when OpenMP is on

.travis.yml, cmake/Settings_Common.cmake
Using the implicit instantiation worked fine for the Futility tests but caused issues when a fuller version of MPACT was compiled.  Moved the implicit instantiation to a command line option to save wall time.
=> Removing implicit instantiation because it caused issues

src/floatingpointchecks.c, src/getSysProcInfo.c
As far as I can tell, these accomplish nothing, so I removed
them to remove compiler warnings about them.
=> Removes 2 empty #pragma statements that were noticed during development

src/PreconditionerTypes.f90, unit_tests/testPreconditionerTypes/testPreconditionerTypes.f90
This was a discussion on #224 that was ultimately deemed outside
the scope of the work.  However, the interface makes more sense
with the matrix being required, and there were no downstream
changes required by this change.
=> Removes OPTIONAL attribute from input matrix for preconditioners

src/Geom_Poly.f90
This is useful for when the PolygonType is modified by an external
code and these values should be updated without completely clearing
and reinitializing the object.
=> Move PolygonType centroid and area calculations into their own routines

src/ParallelEnv.f90
Fixes an incorrect preprocessor symbol in ParallelEnv.  The `||` operator cannot be used with `#ifdef`.  If multiple variables are defined, they need to be checked using `#if defined(var1) || defined(var2)`.
Also using this to test fixes for the travis-ci hooks.
=> Fix a preprocessor statement in ParallelEnv

src/EigenvalueSolverTypes.f90, src/LinearSolverTypes.f90, src/LinearSolverTypes_Multigrid.f90, src/MatrixTypes_PETSc.f90, src/ODESolverTypes.f90, src/ParallelEnv.f90, src/PartitionGraph.f90, src/PreconditionerTypes.f90, src/VectorTypes.f90, src/VectorTypes_PETSc.f90, unit_tests/testEigenvalueSolver/testEigenvalueSolver.f90, unit_tests/testLinearSolver/testLinearSolver.f90, unit_tests/testLinearSolver_Multigrid/testLinearSolver_Multigrid.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90, unit_tests/testMatrixTypes/testMatrixTypesParallel.f90, unit_tests/testODESolver/testODESolver.f90, unit_tests/testParTPLPETSC/testParTPLPETSC.f90, unit_tests/testPartitionGraph/testPartitionGraph.f90, unit_tests/testPreconditionerTypes/testPreconditionerTypes.f90, unit_tests/testTPLPETSC/testTPLPETSC.f90, unit_tests/testTPLSLEPC/testTPLSLEPC.f90, unit_tests/testVectorTypes/testVectorTypes.f90, unit_tests/testVectorTypes/testVectorTypesParallel.f90
This MR encompasses the changes necessary to use PETSc 3.12.4.  I think eventually, we'll want to consider deprecating older versions of PETSc support, but at present should preserve any previous versions supported.
=> PETSc 3.12.4 Upgrade

src/Futility_DBC.f90
Description:
Getting a traceback with Intel requires calling the C abort procedure, so
this should be called from Futility_DBC when the compiler is Intel.
CASL Ticket # - 6264
=> Add error stop for Intel compiled code

unit_tests/testVectorTypes/testVectorTypes.f90
Fixing build issue introduced in testVectorTypes for GCC 8.3.
=> Hotfix testVectorTypes GCC8.3

src/AndersonAcceleration.f90, src/VectorTypes.f90, unit_tests/testAndersonAcceleration/testAndersonAcceleration.f90
The native Anderson Acceleration ability had a restriction in place that required that a solution step be taken at least once before the solver was reset. This normally makes sense, however, for multistate cases where only a single iteration will be taken on a state this restriction becomes a problem. This MR simply removes the restriction.
=> Remove Call Restriction On Anderson Reset

src/VTUFiles.f90
This enables serial cases to write pvtu files, which provides nothing more than a user convenience when using the written files in visit.
=> Enable editing pvtu files for serial cases

src/FileType_HDF5.f90, unit_tests/testTimes/testTimes.f90
Differences in time keeping on virtual machines and the window subsystem for linux can be problematic for the current testTimes.  This reworks the test to simply check that the elapsed time is increasing properly and not to anything insane, rather than relying on more precise amounts of time.
=> Hotfix test times

src/ArrayUtils.f90, unit_tests/testArrayUtils/testArrayUtils.f90
This allows a single entry of an array to be replaced by an array.  It's basically a convenience function to handle certain types of array resize operations.
=> Add replace_entry interface to ArrayUtils

src/Strings.f90, unit_tests/testStrings/testStrings.f90
Adds a constructor for string types.  This allows interfaces to be defined
only taking in string types, and the client code can simply cast native characters
to the string type in the call to the routine if needed.  Specifically this can
be useful for testing where hard-coded strings will be common.
=> Add constructor for string types

ProjectName.cmake, unit_tests/testGenReqTables/CMakeLists.txt
The main purpose here is to make it possible for other projects to consistently locate Futility cmake files via the `Futility_SRC_DIR` variable.  However, I also discovered a test had not been given a test label either, so I fixed that in the process.
=> Test labels

src/ArrayUtils.f90, unit_tests/testArrayUtils/testArrayUtils.f90
Ensures that an allocated array is always returned by getUnique
=> Fix getUnique to always return allocated array

src/LinearSolverTypes_Multigrid.f90, src/MatrixTypes_Native.f90, unit_tests/testLinearSolver/testLinearSolverParallel.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90
Adds need ifdef/USE statements to get Futility tests building in 8.3 with new TPLs
=> Fix petsc errors to migrate from petsc 3.6 to 3.12

src/MatrixTypes_Native.f90, unit_tests/testMatrixTypes/testMatrixTypes.f90
The serial banded matrix requires an exact nnz value count to function. However, this was improved for the parallel versions, which instead treat nnz as an upper bound.
This MR updates the serial behavior to match the parallel behavior, which resolves several ongoing problems with implementing native CMFD in the serial debug test cases.
=> Relaxed nnz requirement on serial banded matrices

src/ParallelEnv.f90
In some cases, HUGE(...) was not being overwritten if there
were empty strings, which could then lead to errors in the
send/receive.  This was fixed by using -HUGE(...) instead,
and then only performing the send/receive for rank >= 0
=> Fix potential for bad ranks to be used in string gathers

src/LinearSolverTypes.f90
Description:
For this newer version of PETSc, a parallel run using SuperLU_dist needs to
specifically call that solver (not SuperLU, which only works for serial).  Older
versions of PETSc allowed the solver to be set to SuperLU whether it was serial
or parallel.
CASL Ticket # - 4661
=> Fix for PETSc 3.12.4

src/LinearSolverTypes.f90
Just use superlu_dist for both serial and parallel solves to fix valgrind defects
=> Fix superlu_dist issues by using it for serial solvers too

src/XDMFMesh.f90
Two myName parameters were unused.
=> Remove unused parameters in XSMFMesh

src/Futility_DBC.f90
This logical will allow client codes finer control.  Before they could determine whether the code stopped or not when tripping a DBC check, but this additional logical allows control of whether or not a message is printed.  Two different levels are appropriate since some DBC statements might result in thousands of lines of backtrace if stopping on failure is disabled.
=> Add a DBC_FAIL_VERBOSE logical

src/EigenvalueSolverTypes.f90, unit_tests/testEigenvalueSolver/testEigenvalueSolver.f90
Something was being cleared twice in Trilinos due to how we
were calling various functions.  This fixes that issue and
fixes 2 other unrelated valgrind defects.  The test now passes
in release-debug with no memory leaks or other valgrind defects.
=> Fixes defects in testEigenvalueSolver

src/VTKFiles.f90, src/VTUFiles.f90
This is needed for certain types of integer data to plot correctly as boundary plots.
=> Add fieldData to vtkMeshType to aid VTU filled boundary edits

src/MatrixTypes_Native.f90
The MPI_IN_PLACE keyword needs to be swapped from the send to recv buffer in an allreduce call.
Current implementation fails (silently) to correctly sum data on some problems (including 3-mini in the native CMFD heavies.
This was not observed before, and I don't know why it is an issue now. The layout of the CMFD matrix should not have changed. The only change made before observing this issue was the update of the MPACT branch to latest master.
Additionally, the documentation for MPI seems to indicate the MPI_IN_PLACE keyword is valid in either the send/recv buffer. However, this is clearly not the case here.
=> Hotfix for Distributed Matrix Initialization
